### PR TITLE
Update intro.rst

### PR DESCRIPTION
**Pull request by quater**
Python 2.7.10 dependency added. https://github.com/jrief/django-shop/issues/50

### CODE REVIEW

**Comment by rfleschenberg** [comment]
Thank you for the PR!

I don't think we really require 2.7.10. Any version of 2.7 is probably fine, even though, like Django, we officially recommend the latest minor version. Can you update the PR to say something like "Python 2.7 (latest minor version recommended)" or such?

It's just a minor point, but I think we should avoid scaring users of distrbutions who ship Python 2.7.9 or such.

**Comment by rfleschenberg** [comment]
Also, we should probably add a note that we currently only support Django 1.8.

**Comment by quater** [comment]
Applied the changes as suggested

**Comment by rfleschenberg** [comment]
Merging. Thanks!

**Pull request merged**
