### PR TITLE
Use the new django management command definition (ArgumentParser)

### PR DESCRIPTION
**Pull request by khchine5**
#61

### CODE REVIEW

**Comment by jrief** [comment]
Oh, thanks for fixing this. I created the issue for myself.

**Comment by khchine5** [comment]
Oh sorry , I didn't know that.

**Comment by jrief** [comment]
Never mind. I did not expect anybody else would fix this. Thanks anyway.

**Comment by khchine5** [comment]
Actually, I plan to use Django-shop and I am currently at the discovering stage. It is really an interesting framework. I would help to improve it.

**Pull request merged**
